### ISSUE TITLE
traverson github org

### ISSUE THREAD

**Issue by basti1302** [traverson/traverson-promise#8]
Hi there,

I (the maintainer of traverson) only found out about this project just now. I really like it that someone made the effort to provide a promise adapter for Traverson, independent of Angular. That's something that has been requested by Traverson users a number of times.

If you had told me about the project, I would have linked to it from Traverson's readme/user guide :-) I'll certainly will do this now, if you don't mind.

This project (and another project closely related to Traverson, punkstarman/traverson-traversal) reminded me of something I had planned for a while now, but never got around to do it: It might make sense to move all of my traverson projects (traverson, traverson-hal, traverson-angular, ...) to a GitHub organization, so they are no longer tied to my user account (basti1302).

I actually created the org today (https://github.com/traverson), but did not yet move any projects.

It might be even cooler to gather all traverson-related projects there, not only the ones written/maintained by me.

What do you think about that? How would you feel about transferring this project into a `traverson` GitHub organization? Of course, you will still have full control over the project and full access rights to the project (and possibly commit bits for the other traverson projects, too, if you are interested). I certainly don't want this to feel like I want to take the project away from you or something.

Also, npm just announced free organizations for open source projects. A second step might be to also use an npm organization for traverson, but this might be a more difficult transition, not sure if its worth it - we can think about that later.

Anyway, let me know what you think about that.

**Comment by xin-nie** [comment]
Hi Bastian,

It would be a great idea. But I'm about to merge my two github accounts (and might delete this one), and I might need to transfer this project to another account first. So could we do the transfer after the merge to avoid any conflict?

**Comment by basti1302** [comment]
Sure, there is absolutely no need to rush anything. I also think that I should move the main traverson projects first and there's some work involved, it might be a while until I get around to do that. I'll ping you again when that is done.

**Comment by basti1302** [comment]
Just to give you an update: I had some time today so the move of my traverson repositories to the new org is now completed. If you still want to move this repo into the org, just give me a ping when you are done with merging your accounts and when it is convenient for you to transfer the repo.

I sent invites for the org to both of you accounts (xin-nie and nie-xin, right?), feel free to accept the invite with the account that you plan to keep in the long term.

**Comment by xin-nie** [comment]
Hi Bastian, 

I finally got some time to move this repo, so it's ready to move to traverson org repositories.

**Comment by basti1302** [comment]
Okay, if you want to move it, follow this steps: 
* Go to https://github.com/xin-nie/traverson-promise
* Click on Settings (upper right corner)
* Scroll down to the section titled "Danger Zone"
* Click "Transfer"
* Enter traverson-promise in the first input field and traverson in the second

That should be it.
